# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3859b92fc8b586e5a68c1bba16844634fbfb7de654a85ff6884dd5330d8ae57d19269e1d350700b8e347cefcc4690b9d30a1d96acb97b99d10743a75a9cfa27

test:
  secret_key_base: 5d9b9864b4864f1526e80ac111d3064087baf94037e1c059584fe12dcda88ee7511fb590af40f1d8d76cbbee8de844af35851994e72f916ed0c2f25599112dce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
